import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    padding: 10,
    marginTop: 20,
    backgroundColor: "white",
  },
  innerContainer: {
    marginTop: 30,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  image: {
    backgroundColor: "white",
    borderRadius: 8,
    width: 200,
    height: 200,
    padding: 10,
    margin: 10,
    justifyContent: "center",
    resizeMode: "contain",
    marginRight: 80,
  },
  textParts: {
    marginTop: 30,
  },
  title: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 8,
    backgroundColor: "#DCDCDC",
    fontSize: 15,
    padding: 10,
    margin: 10,
    fontSize: 20,
  },
  desc: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 8,
    backgroundColor: "#DCDCDC",
    fontSize: 15,
    padding: 10,
    margin: 10,
    fontSize: 20,
  },
  price: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 8,
    backgroundColor: "#DCDCDC",
    fontSize: 15,
    padding: 10,
    margin: 10,
    fontSize: 20,
  },
  category: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 8,
    backgroundColor: "#DCDCDC",
    fontSize: 15,
    padding: 10,
    margin: 10,
    fontSize: 20,
  },
  button: {
    margin: 5,
    borderRadius: 8,
    backgroundColor: "#00695C",
    padding: 8,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    color: "white",
  },
});
